/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/cauldron.glb --output src/components/Cauldron/model.jsx 
*/

import * as THREE from "three";
import { useFrame } from "@react-three/fiber";
import {
  useGLTF,
  MeshDistortMaterial,
  Sparkles,
  GradientTexture,
  useCursor,
} from "@react-three/drei";
import { useMemo, useRef, useState } from "react";
import { useBrew } from "@/features/brew/store";

// Served from public/ (not src/assets) and prefixed with Vite's BASE_URL: a
// bare "./src/assets/..." string is never picked up by Vite's build pipeline
// (it only works in dev, where Vite happens to serve the whole project root),
// so the production build was silently falling back to index.html for both
// of these — same class of bug as the ingredient GLBs' hardcoded "/models/".
const modelPath = `${import.meta.env.BASE_URL}models/cauldron.glb`;
const liquidNormalPath = `${import.meta.env.BASE_URL}normals/water.jpg`;

// Target bloom luminance for the liquid. emissiveIntensity is derived each frame
// as LIQUID_GLOW / colorLuminance so every brew color blooms to about this much.
const LIQUID_GLOW = 3.0;

export function Model({ liquidColor, bubbleColor, ...props }) {
  const { nodes, materials } = useGLTF(modelPath);
  const liquidMat = useRef();
  const toggleDial = useBrew((s) => s.toggleDial);
  const brewPulse = useBrew((s) => s.brewPulse);
  const [hovered, setHovered] = useState(false);
  useCursor(hovered);
  const targetColor = useMemo(
    () => new THREE.Color(liquidColor),
    [liquidColor]
  );

  const swirl = useRef(0);
  const prevPulse = useRef(0);

  const normalMap = useMemo(() => {
    const tex = new THREE.TextureLoader().load(liquidNormalPath);
    tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
    tex.repeat.set(1, 1); // ↓ fewer tiles (was default 1x1 anyway)
    tex.center.set(0.5, 0.5); // rotate about the middle for the swirl
    return tex;
  }, []);

  useFrame((_, delta) => {
    // a brew kicks off a decaying swirl
    if (brewPulse !== prevPulse.current) {
      prevPulse.current = brewPulse;
      swirl.current = 1;
    }
    // scroll + (during a swirl) spin the surface ripples
    normalMap.offset.y =
      (normalMap.offset.y + delta * (0.02 + swirl.current * 0.5)) % 1;
    normalMap.offset.x =
      (normalMap.offset.x + delta * (0.01 + swirl.current * 0.25)) % 1;
    if (swirl.current > 0) {
      normalMap.rotation += delta * swirl.current * 7;
      swirl.current = Math.max(0, swirl.current - delta * 0.5);
    }
    // ease the liquid toward the current brew color
    if (liquidMat.current) {
      liquidMat.current.color.lerp(targetColor, 0.08);
      liquidMat.current.emissive.lerp(targetColor, 0.08);
      // Bloom triggers on luminance, so a fixed emissiveIntensity makes light
      // colors bloom way harder than dark ones. Normalize by the emissive's
      // luminance so every brew glows to roughly the same level (clamped so
      // very dark colors don't blow out and very light ones still read).
      const e = liquidMat.current.emissive;
      const lum = 0.2126 * e.r + 0.7152 * e.g + 0.0722 * e.b;
      liquidMat.current.emissiveIntensity = THREE.MathUtils.clamp(
        LIQUID_GLOW / Math.max(lum, 0.05),
        3,
        14
      );
    }
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Liquid.geometry}
        scale={[1.168, 0.995, 1.168]}
        onClick={(e) => {
          e.stopPropagation();
          toggleDial();
        }}
        onPointerOver={(e) => {
          e.stopPropagation();
          setHovered(true);
        }}
        onPointerOut={() => setHovered(false)}
      >
        <meshStandardMaterial
          ref={liquidMat}
          color={liquidColor}
          emissive={liquidColor}
          emissiveIntensity={10}
        />
      </mesh>
      {/* whole iron body is also a click target → easy to open the dial */}
      <group
        scale={[1.174, 1, 1.174]}
        onClick={(e) => {
          e.stopPropagation();
          toggleDial();
        }}
        onPointerOver={(e) => {
          e.stopPropagation();
          setHovered(true);
        }}
        onPointerOut={() => setHovered(false)}
      >
        <mesh
          geometry={nodes.Sphere002.geometry}
          material={materials.Cauldron}
        />
        <mesh
          geometry={nodes.Sphere002_1.geometry}
          material={materials.Cauldron}
        />
      </group>
      {/* <Sparkles
        count={50}
        scale={[1.2, 0.5, 1.2]}
        size={8}
        speed={0.4}
        noise={0.5}
        color={bubbleColor}
        position={[0, 0.1, 0]}
      /> */}
    </group>
  );
}

useGLTF.preload(modelPath);
