/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/cauldron.glb --output src/components/Cauldron/model.jsx 
*/

import * as THREE from "three";
import { useFrame } from "@react-three/fiber";
import {
  useGLTF,
  MeshDistortMaterial,
  Sparkles,
  GradientTexture,
} from "@react-three/drei";
import { useMemo } from "react";

const modelPath = "./src/assets/models/cauldron.glb";
const liquidNormalPath = "./src/assets/normals/water.jpg";

export function Model({ liquidColor, bubbleColor, ...props }) {
  const { nodes, materials } = useGLTF(modelPath);

  const normalMap = useMemo(() => {
    const tex = new THREE.TextureLoader().load(liquidNormalPath);
    tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
    tex.repeat.set(1, 1); // ↓ fewer tiles (was default 1x1 anyway)
    return tex;
  }, []);

  useFrame((_, delta) => {
    // gentle scroll
    normalMap.offset.y = (normalMap.offset.y + delta * 0.02) % 1;
    normalMap.offset.x = (normalMap.offset.x + delta * 0.01) % 1;
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Liquid.geometry}
        scale={[1.168, 0.995, 1.168]}
        onClick={() => console.log("clicked")}
        style={{ cursor: "pointer" }}>
        <meshStandardMaterial
          color={liquidColor}
          emissive={liquidColor}
          emissiveIntensity={10}
        />
      </mesh>
      <group scale={[1.174, 1, 1.174]}>
        <mesh
          geometry={nodes.Sphere002.geometry}
          material={materials.Cauldron}
        />
        <mesh
          geometry={nodes.Sphere002_1.geometry}
          material={materials.Cauldron}
        />
      </group>
      {/* <Sparkles
        count={50}
        scale={[1.2, 0.5, 1.2]}
        size={8}
        speed={0.4}
        noise={0.5}
        color={bubbleColor}
        position={[0, 0.1, 0]}
      /> */}
    </group>
  );
}

useGLTF.preload(modelPath);
