/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/demo-espresso-machine.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const _modelPath = "./models/demo-espresso-machine.glb";

export default function EspressoMachine(props) {
  const { nodes, materials } = useGLTF(_modelPath);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  );
}

useGLTF.preload(_modelPath);
